INSERT INTO usuario (nome, email) VALUES ('Maria', 'maria@email.com');
INSERT INTO livros (titulo, autor, ano_publi ) 
VALUES ('Um defeito de Cor', 'Ana Maria Gonçalves', 2006),
		('Olhos Dágua','Conceição Evaristo',2014),
        ('Seja como a água Bruce Lee','Shannon Lee',2020),
        ('O fim da Procrastinação','Petr Ludwing',2013),
        ('Não começou com você Trauma Familiar','Mark Wolynn ',2016),
        ('A gente mira no amor e acerta a solidão','Ana Suuy',2022),
        ('Mais esperto que o diabo','Napoleon Hill',1938),
        ('A coragem de não agradar','Ichiro Kishimi e Fumitake Koga',2013),
        ('As armas da Persuasão','Robert Cialdini',1984),
        ('Mentes Perigosas','Ana Beatriz Barbosa Silva',2008),
        ('Mente que ama demais','Ana Beatriz Barbosa Silva',2011),
        ('OO poder dos quietos','Susan Cain',2012),
        ('A coragem de ser Imperfeito','Brené Brown',2012),
        ('Minutos de Sabedoria','C. Torres Pastorino',1960),
        ('A arte de Pensar','Ernest Dimnet',1928),
        ('A vida Intelectual','A. D. Sertillanges',1921),
        ('A arte de Ler','Emilio Faguet',1912),
        ('Memórias do Subsolo','Fiódor Dostoiévski',1864),
        ('O Idiota','Fiódor Dostoiévski',1869),
        ('Ansiedade Digital: Como Enfrentar o Mal do Milênio','Augusto Cury',2019),
        ('Dracula', 'Bram Stoker', 1897),
        ('Frankenstein','Mary Shelley', 2007),
        ('Timidez', 'Christopher Lane', 2007),
        ('A hora do Pesadelo', 'Jeffrey Cooper', 1984),
        ('Sexta Feira 13', 'Simon Hawke', 1987),
        ('Star Wars Trilogia', 'George Lucas', 1976),
        ('O Fantasma da Ópera', 'Gaston Leroux', 1910),
        ('O colecionador', 'John Fowles', 1963),
        ('A vida não me assusta', 'Maya Angelou' ,1978),
        ('O hobbit', 'J.R.R. Tolkien', 1937),
        ('Senhor dos Anéis', 'J.R.R. Tolkien', 1954),
        ('Capitães da Areia', 'Jorge Amado', 1937),
        ('Você Fica Tão Sozinho às Vezes que Até faz Sentido', 'Charles Bukowski', 1986),
        ('A hora da Estrela', 'Clarice Lispector', 1977),
        ('Morte na Praia', 'Agatha Christie', 1941),
        ('A biblioteca da meia-noite', 'Matt Haig', 2020),
        ('A boa sorte', 'Álex Rovira e Fernando Trías de Bes', 2004),
        ('Imitação de Cristo', 'Tomás de Kempis', 1418),
        ('Confissões', 'Santo Agostinho', 397),
        ('A Prática da Presença de Deus', 'Irmão Lawrence', 1962),
        ('Abusado - O dono do morro Dona Marta', 'Caco Barcellos', 2003),
        (' Um estudo em vermelho', 'Arthur Conan Doyle', 1887 );
